Scm widget endpoints
hygieia/api pull request #251
Opened 2021-12-09 19:16 UTC by tatlax3636

- Added 2 endpoints for UI use (for SCM widget): combined issue/pull endpoint and commits endpoint
- Adding accompanying service functions

2021-12-09 20:01 UTC, nameisaravind requested changes

2021-12-09 20:01 UTC, nameisaravind commented on src/main/java/com/capitalone/dashboard/service/GitRequestServiceImpl.java
> +        return new DataResponse<>(results, new Date().getTime()) ;
use System.currentTimeMillies

2021-12-09 21:26 UTC, tatlax3636 commented on src/main/java/com/capitalone/dashboard/service/CommitServiceImpl.java
> +        int numberOfDays = request.getNumberOfDays() == null ? 14 : request.getNumberOfDays();
@nameisaravind sorry I don't understand what you mean. Can you give an example?

2021-12-09 21:27 UTC, tatlax3636 commented on src/main/java/com/capitalone/dashboard/service/GitRequestService.java
> +import com.capitalone.dashboard.model.LibraryPolicyResult;
Done

2021-12-09 21:27 UTC, tatlax3636 commented on src/main/java/com/capitalone/dashboard/rest/WidgetController.java
> +import com.capitalone.dashboard.model.*;
Done

2021-12-09 21:47 UTC, tatlax3636 commented on src/main/java/com/capitalone/dashboard/service/CommitServiceImpl.java
> +        int numberOfDays = request.getNumberOfDays() == null ? 14 : request.getNumberOfDays();
Done

2021-12-10 20:56 UTC, nameisaravind approved these changes
lgtm

2021-12-13 14:24 UTC, merged